.TH GRCC "1" "2024-11-18" "grcc v3.11.0.0git-829-g889721a8" "User Commands"
.SH NAME
grcc \- Gnu Radio Companion Compiler
.SH DESCRIPTION
Just compile a gnuradio companion flowgraph without invoking the gui.
.PP
Given an input GRC file and an output directory, create a runnable
application in the output directory.
.SH "SEE ALSO"
gnuradio-companion(1)
